### ISSUE TITLE
Capturing the stdout and stderr?

### ISSUE THREAD

**Issue by brspurri** [pygridtools/drmaa-python#12]
Is there a supported way to capture the `stdout/stderr` of each job?
Or would I have to add a `> output_filename` to the job template arguments list?

**Comment by vipints** [comment]
Hi @dan-blanchard, I am having trouble to get the `stderr` file of each job to the specified location defined in the `JobTemplate`. I specified the `jt` with output and error path but I am only able to get the `stdout` file when using with Torque. 

Do you any suggestion. thanks

**Comment by vipints** [comment]
@dan-blanchard I solved this problem. `jt.joinFiles=True` was true in my case.
