### ISSUE TITLE
binary / script flag

### ISSUE THREAD

**Issue by cancan101** [pygridtools/drmaa-python#26]
When using `qsub` with SGE, there is a flag `-b` that specifies whether to treat the command as a binary or script. if `-b y`, `qsub` will assume the command is available on the compute hosts (and not necessarily the submission host) whereas if `-b n`, the file will be copied over from the submission.

 Is there a way to do that in `drmaaa` or should I use either `nativeSpecification` or something like `transferFiles`?

Full text from man page:

       -b y[es]|n[o]
              Available for qsub, qrsh only. Qalter does not allow changing this option. This option cannot be embedded in the script file itself.

              Gives  the  user the possibility to indicate explicitly whether command should be treated as binary or script. If the argument of -b is ’y’, then command  may be a binary or script.  The command might
              not be accessible from the submission host.  Nothing except the path of the command will be transferred from the submission host to the execution host. Path aliasing will be applied  to  the  path  of
              command before it is executed.

              If  the  argument  of  -b is ’n’ then command needs to be a script, and it will be handled as such. The script file has to be accessible by the submission host. It will be transferred to the execution
              host. qsub/qrsh will search directive prefixes within scripts.

              qsub will implicitly use -b n, whereas qrsh will apply the -b y option if nothing else is specified.

              The value specified with this option or the corresponding value specified in qmon will only be passed to defined JSV instances if the value is yes.  The name of the parameter will be b. The value will
              be y also when the long form yes was specified during submission.  (See -jsv option below or find more information concerning JSV in jsv(1).)

              Please  note  that submission of command as a script (-b n) can have a significant performance impact, especially for short running jobs and big job scripts.  Script submission adds a number of opera-
              tions to the submission process: The job script needs to be
              - parsed at client side (for special comments)
              - transferred from submit client to qmaster
              - spooled in qmaster
              - transferred to execd at job execution
              - spooled in execd
              - removed from spooling both in execd and qmaster once the job is done
              If job scripts are available on the execution nodes, e.g. via NFS, binary submission can be the better choice.

**Comment by dan-blanchard** [comment]
If you just want to have a script run on the cluster, you do not need to specify anything special, since (like the `qsub` docs say, `-b n` is the default).

`transferFiles` could use better documentation (as I didn't even know what it did until now).  According to the [DRMAA C docs](http://linux.die.net/man/3/drmaa_attributes), this is what `transferFiles` is useful for:

> Specifies, which of the standard I/O files (stdin, stdout and stderr) are to be transferred to/from the execution host. If not set, defaults to "". Any combination of 'e', 'i' and 'o' may be specified. See drmaa_input_path, drmaa_output_path and drmaa_error_path for information about how to specify the standard input file, standard output file and standard error file. The file transfer mechanism itself must be configured by the administrator (see sge_conf(5) ). When it is configured, the administrator has to enable drmaa_transfer_files. If it is not configured, "drmaa_transfer_files" is not enabled and can't be used.

**Comment by cancan101** [comment]
@dan-blanchard So how I get `-b y` then, just `nativeSpecification`?

**Comment by dan-blanchard** [comment]
Yup.  For anything that's not listed in the [`JobTemplate` docs](http://drmaa-python.readthedocs.org/en/latest/drmaa.html#drmaa.JobTemplate), you have to use `nativeSpecification`. 

Note:  You might want to actually click the `source` link to view the code for `JobTemplate`, because sphinx didn't pick up the docstrings for all of the `JobTemplate` attributes for some reason.  The list is complete, but the descriptions are missing.

**Comment by cancan101** [comment]
I am not sure I understand the difference between `transferFiles` and `errorPath`, `outputPath`, `inputPath`.

**Comment by dan-blanchard** [comment]
`errorPath`, `outputPath`, and `inputPath` are all paths to files located on worker nodes (and not the machine you're submitting from) which will contain STDERR, STDOUT, and STDIN (respectively).  `transferFiles` will transfer any combination of those files the files located at those paths from the worker nodes back to your submitting host upon job completion.  I've never used a cluster that was configured to support that though, so I don't know much about that.

**Comment by cancan101** [comment]
`qsub` has a `-e` and `-o` option. Is that the same as `errorPath` and `outputPath`? The man page describes as:
    
     -e [[hostname]:]path,...
              Available for qsub, qsh, qrsh, qlogin and qalter only.

              Defines  or  redefines the path used for the standard error stream of the job. For qsh, qrsh and qlogin only the standard error stream of prolog and epilog is redirected.  If the path constitutes an absolute path name,
              the error-path attribute of the job is set to path, including the hostname. If the path name is relative, Grid Engine expands path either with the current working directory path (if the -cwd switch (see above) is  also
              specified)  or with the home directory path. If hostname is present, the standard error stream will be placed in the corresponding location only if the job runs on the specified host. If the path contains a ":" without
              a hostname, a leading ":" has to be specified.

              By default the file name for interactive jobs is /dev/null. For batch jobs the default file name has the form job_name.ejob_id and job_name.ejob_id.task_id for array job tasks (see -t option below).

              If path is a directory, the standard error stream of the job will be put in this directory under the default file name.  If the pathname contains certain pseudo environment variables, their value will  be  expanded  at
              runtime of the job and will be used to constitute the standard error stream path name. The following pseudo environment variables are supported currently:

              $HOME       home directory on execution machine
              $USER       user ID of job owner
              $JOB_ID     current job ID
              $JOB_NAME   current job name (see -N option)
              $HOSTNAME   name of the execution host
              $TASK_ID    array job task index number

              Alternatively  to $HOME the tilde sign "~" can be used as common in csh(1) or ksh(1).  Note, that the "~" sign also works in combination with user names, so that "~<user>" expands to the home directory of <user>. Using
              another user ID than that of the job owner requires corresponding permissions, of course.

              Qalter allows changing this option even while the job executes. The modified parameter will only be in effect after a restart or migration of the job, however.

              If this option or a corresponding value in qmon is specified then this value will be passed to defined JSV instances as parameter with the name e.  (see -jsv option below or find  more  information  concerning  JSV  in
              jsv(1))
