### ISSUE TITLE
Clarification about Memory Leaks

### ISSUE THREAD

**Issue by cancan101** [pygridtools/drmaa-python#29]
The docs state:
>It is the responsibility of the application to make sure one of these two functions [`wait()` or `synchronize()`] is called for every job. Not doing so creates a memory leak. 

What exactly does that mean and where is the leak (in the Python application or in the cluster software)? Does it mean that If I intend my python program to return immediately (like in [example 2](https://github.com/pygridtools/drmaa-python/blob/master/examples/example2.py)), then I should call:
```
retval = s.wait(curjob, drmaa.Session.TIMEOUT_NO_WAIT)
```
before exiting / closing the `session`?

**Comment by dan-blanchard** [comment]
Which docs are you looking at?  The quote you have looks like it's from an older version of our docs.  The [current tutorial section on waiting for a job](http://drmaa-python.readthedocs.org/en/latest/tutorials.html#waiting-for-a-job) makes this pretty clear:

> After a job completes, it leaves behind accounting information, such as exit status and usage, until either `wait()` or `synchronize()` with `dispose` set to `True` is called. It is the responsibility of the application to make sure one of these two functions is called for every job. Not doing so creates a memory leak. Note that calling `synchronize()` with `dispose` set to `True` flushes all accounting information for all jobs in the list. If you want to use `synchronize()` and still recover the accounting information, set `dispose` to `False` and call `wait()` for each job. 

I would not rely on the examples in the `examples` directory directly, as those are old and have not been updated in 5+ years (long before my time as the maintainer).  I really should just remove them.

**Comment by cancan101** [comment]
The quote you pasted is the same as mine (I added the contents within the `[` and `]`).

The section doesn't really answer:
1. Where is this possible memory leak: in the Python application or in the cluster software?
2. If I intend my python program to return immediately, i.e. not wait for the job is just submitted to finish, should call: `retval = s.wait(curjob, drmaa.Session.TIMEOUT_NO_WAIT)` before exiting / closing the `session`?

**Comment by dan-blanchard** [comment]
1.  It's in the cluster scheduler.
2.  I've never actually used `TIMEOUT_NO_WAIT` before (and it's no actually supported by all DRMs that claim to implement DRMAA).  I would experiment and see what happens on your system.

**Comment by cancan101** [comment]
Is there anyway to see that the memory leaking is happening? i.e. is there some command to run that shows the uncleaned up job info?

**Comment by dan-blanchard** [comment]
That would vary with whatever DRM you're using (Grid Engine, Condor, etc.). You'll have to look around for that info. I don't actually work somewhere that uses a DRM system anymore, so it's hard for me to take a look myself.
