### ISSUE TITLE
Fix Travis Badge

### ISSUE THREAD

**Issue by cancan101** [pygridtools/drmaa-python#31]
The current badge shows the build failing when it is not.

Perhaps use:
```
.. image:: https://travis-ci.org/pygridtools/drmaa-python.svg?branch=master
    :target: https://travis-ci.org/pygridtools/drmaa-python
```

**Comment by dan-blanchard** [comment]
I prefer to have the badges point to the stable branch, since that's where the released versions live.  You are correct that it shouldn't say the build is failing though.  There was a weird issue with Travis, so I reran the build.  The badge should be fixed now.
