### ISSUE TITLE
Passing an integer in JobTemplate.args causes a segmentation fault

### ISSUE THREAD

**Issue by xzy3** [pygridtools/drmaa-python#34]
```python
import drmaa

with drmaa.Session() as ses:
   jt = ses.createJobTemplate()
   jt.args = [ 123 ]
   jt.delete()
```

Segmentation fault (core dumped)

looks like the problem is in ```drmaa.helpers.c_char_p_Array_7```
```
ipdb> p string_vector(value)[0]
Segmentation fault (core dumped)
```

**Comment by dan-blanchard** [comment]
Yeah, the arguments have to be strings.  It's what ends up being the argument on the command-line to the script.  Just call `str` on it and you'll be fine.
