### ISSUE TITLE
Session returns empty contact information.

### ISSUE THREAD

**Issue by mackaiver** [pygridtools/drmaa-python#36]
I'm running drmaa-python on a Torque/PBS system. Im using the latest pbs-drmaa library version 1.0.19. I'm running the following piece of code:

```python
import drmaa

def main():
    with drmaa.Session() as s:
        print('A DRMAA object was created')
        print('Supported contact strings: %s' % s.contact) #returns an empty string.
```

Unfortunately s.contact and s.contactString are both empty. Any ideas? Is this a pbs-drmaa related issue? s.drmaaImplementation returns:

    DRMAA for PBS Pro v. 1.0.19 <http://sourceforge.net/projects/pbspro-drmaa/>

**Comment by dan-blanchard** [comment]
The implementation of `s.contact` and `s.contactString` vary between different DRM systems.  We just grab the content from the underlying C library, so it must just be empty on your system.  See [this old email thread](https://www.ogf.org/mail_archive/drmaa-wg/2004/03/msg00047.html) for some discussion.
