### ISSUE TITLE
Error installing via pip on Python 3

### ISSUE THREAD

**Issue by bow** [pygridtools/drmaa-python#40]
Hello drmaa-python developers,

I've recently tried to install the package via `pip`. It worked fine when I'm was Python 2. But on Python 3, I got the following error:

```
Collecting drmaa
  Could not fetch URL https://pypi.python.org/simple/drmaa/: There was a problem confirming the ssl certificate: [Errno 2] No such file or directory - skipping
  Could not find a version that satisfies the requirement drmaa (from versions: )
No matching distribution found for drmaa
```

I tried this with `pip install drmaa` and `pip install drmaa==0.7.6`. It seems like something is either off in the PyPI metadata or for some reason the actual package is not uploaded correctly.

Any ideas what may be going wrong there?

Thanks in advance for looking into this :),

**Comment by bollig** [comment]
Not sure about this, but I've noticed that a lot of Python packages
recently require "requests[security]" as an unspoken dependency for SSL to
work. Try giving this a shot:

pip install --upgrade requests[security]

Cheers,
-E

On Wednesday, July 6, 2016, Wibowo Arindrarto <notifications@github.com>
wrote:

> Hello drmaa-python developers,
>
> I've recently tried to install the package via pip. It worked fine when
> I'm was Python 2. But on Python 3, I got the following error:
>
> Collecting drmaa
>   Could not fetch URL https://pypi.python.org/simple/drmaa/: There was a problem confirming the ssl certificate: [Errno 2] No such file or directory - skipping
>   Could not find a version that satisfies the requirement drmaa (from versions: )
> No matching distribution found for drmaa
>
> I tried this with pip install drmaa and pip install drmaa==0.7.6. It
> seems like something is either off in the PyPI metadata or for some reason
> the actual package is not uploaded correctly.
>
> Any ideas what may be going wrong there?
>
> Thanks in advance for looking into this :),
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pygridtools/drmaa-python/issues/40>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AALbQo-ti3W75wpHC0P1nYOoH5xskslgks5qS9x7gaJpZM4JGSEm>
> .
>


-- 
-Evan Bollig
bollig@gmail.com
boll0107@umn.edu

**Comment by bow** [comment]
Woah, that actually worked! I didn't expect this given that Python 2 was working, but it's clear that I overlooked something then.

Anyway, thanks a lot :)!
