### ISSUE TITLE
Release v0.7.9

### ISSUE THREAD

**Issue by jakirkham** [pygridtools/drmaa-python#67]
Would be nice to get a fresh patch release given some of the fixes included since `v0.7.8`.

**Comment by desilinguist** [comment]
@jakirkham, I agree. Would you want me to work on the release? If so, I can work on it later in June as I’m quite swamped at work for the short term.

**Comment by jakirkham** [comment]
That sounds fine. Thanks.

**Comment by xzy3** [comment]
+1 I have a project that needs a post v0.7.8 fix that's already been committed. I'm building directly from git right now.

**Comment by jakirkham** [comment]
It’d be nice if we could get PR ( https://github.com/pygridtools/drmaa-python/pull/73 ) and PR ( https://github.com/pygridtools/drmaa-python/pull/65 ) in first so we can have Python 3.7 support.

**Comment by jakirkham** [comment]
Now that those are in, agree that we should be ready for a release.

**Comment by desilinguist** [comment]
Sorry, this keeps getting pushed. I’ll try and get back to it after I’m back from vacation in a few weeks.

**Comment by desilinguist** [comment]
Actually, I am really swamped with other stuff and could use help with this.

**Comment by jakirkham** [comment]
How can we help?

**Comment by xzy3** [comment]
I'm happy to help too.

**Comment by desilinguist** [comment]
If you guys could draft the release notes, that'd be really useful.

**Comment by xzy3** [comment]
- Removed use of `StopIteration` from `run_bulk_job`; a behavior deprecated by PEP479 for Python 3.5+.
- Added licence file to the wheel.
- Deprecated Python 2.6.x, and Python 3.3.x.
- Added testing for Python 3.7.x

That's everything I saw in the git log.

**Comment by jakirkham** [comment]
Is there a particular file they should go in?

**Comment by desilinguist** [comment]
You can draft a new release under releases and put them there. I’ll make a
package and upload to pypi and then make the release public.

**Comment by jakirkham** [comment]
I lack the permissions to do that unfortunately.

**Comment by desilinguist** [comment]
Ah, no worries. I’ll take care of it tomorrow.

**Comment by desilinguist** [comment]
I have released 0.7.9 and updated the package on PyPI as well. Please test and let me know if all looks good and I'll close the issue. Thanks again for your patience!

**Comment by jakirkham** [comment]
Thanks @desilinguist. Much appreciated. 😄

**Comment by desilinguist** [comment]
So, I am assuming everything looks good and I can close this?
